name: upd
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=3.2.6 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true
    assets:
        - assets/images/Image.png
    fonts:
        - family: Inter
          fonts:
              - asset: fonts/Inter-Bold.ttf
                weight: 700
              - asset: fonts/Inter-SemiBold.ttf
                weight: 600
              - asset: fonts/Inter-Medium.ttf
                weight: 500
              - asset: fonts/Inter-Regular.ttf
                weight: 400
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Bold.ttf
                weight: 700
              - asset: fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: fonts/Poppins-Medium.ttf
                weight: 500
              - asset: fonts/Poppins-Regular.ttf
                weight: 400
        - family: Roboto
          fonts:
              - asset: fonts/Roboto-Bold.ttf
                weight: 700
              - asset: fonts/Roboto-Medium.ttf
                weight: 500
              - asset: fonts/Roboto-Regular.ttf
                weight: 400
